<!doctype html>
<html lang="en">
  <head>
    <title>Hello</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <?php
    $session = my_app()->session();
    if(!$session->has('counter')){
        $session->set('counter', 0);
    }
    $session->set('counter', $session->get('counter') + 1);
    ?>
    <h1>Hello world ke-<?= $session->get('counter') ?>!</h1>
    <p>Write from file <?=__FILE__?></p>
  </body>
</html>